name: Add Internship Experience
on:
  workflow_dispatch:
    inputs:
      member-name:
        description: 'Name of the member'
        required: true
        default: 'missing (error) !'

      intern-exp-data:
        description: 'stringifyed JSON containing intern exp'
        required: true
        default: 'missing (error) !'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: python ./.github/scripts/add-intern-exp.py ${{ github.event.inputs.intern-exp-data }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Add Intern Experience of "${{ github.event.inputs.member-name }}"
          title: '[Google Form] Add Intern Experience'
          body: >
            Add the Internship Experience of "${{ github.event.inputs.member-name }}" submitted through google form
            This PR is auto-generated by 
            [create-pull-request](https://github.com/peter-evans/create-pull-request).
          labels: automated pr